Name:           ros-hydro-segbot-logical-translator
Version:        0.3.1
Release:        0%{?dist}
Summary:        ROS segbot_logical_translator package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/segbot_logical_translator
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-bwi-mapper
Requires:       ros-hydro-bwi-msgs
Requires:       ros-hydro-bwi-planning-common
Requires:       ros-hydro-map-msgs
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-move-base-msgs
Requires:       ros-hydro-multi-level-map-msgs
Requires:       ros-hydro-multi-level-map-utils
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-segbot-navigation
Requires:       ros-hydro-tf
Requires:       ros-hydro-utexas-gdc
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-bwi-mapper
BuildRequires:  ros-hydro-bwi-msgs
BuildRequires:  ros-hydro-bwi-planning-common
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-map-msgs
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-move-base-msgs
BuildRequires:  ros-hydro-multi-level-map-msgs
BuildRequires:  ros-hydro-multi-level-map-utils
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-tf

%description
High-level navigation application for the segbot allowing the segbot to approach
and gothrough doors. The application can also be used to determine the segbot's
logical location, as well as sense when a door in front of the robot is open or
not.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Mar 31 2015 Piyush Khandelwal <piyushk@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Tue Mar 24 2015 Piyush Khandelwal <piyushk@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

