controller_frequency: 5.0
TrajectoryPlannerROS:

  sim_time: 1.5

  dwa: true
  vx_samples: 15
  vtheta_samples: 30

  max_vel_x: 1.00
  min_vel_x: 0.50
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.3

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.5

  goal_distance_bias: 0.9
  path_distance_bias: 0.2
  occdist_scale: 0.01

  heading_lookahead: 0.325

  oscillation_reset_dist: 0.05
  holonomic_robot: false

  acc_lim_th: 0.785
  acc_lim_x: 1.0
  acc_lim_y: 1.0
